# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Project
project.version=1.1.0
project.group=kr.rtustudio
project.author=IPECTER

# Common
java.version=21
minecraft.version=1.21.3

# Bukkit
plugin.main=kr.rtustudio.supplybox.SupplyBox
plugin.api.version=1.21.3
plugin.paper=true

# RSFramework
framework.version=4.7.9
