displayName: "<gray>Example</gray>"

alert:
  minecraft: true
  discord: false

# nexo:id
# itemsadder:namespace:id
# oraxen:id
# minecraft:block
block: "minecraft:chest"

# nexo:id
# itemsadder:namespace:id
# oraxen:id
# mmoitems:category:id
# minecraft:item
item:
  box: "minecraft:chest"
  key: "minecraft:trial_key"

# drop / inventory / give
interact: "inventory"

loot: "Example"

