# amount to select item
# 선택할 아이템 수
select:
  min: 2
  max: 2

items:
  # nexo:id
  # itemsadder:namespace:id
  # oraxen:id
  # mmoitems:category:id
  # minecraft:item
  minecraft:stone:
    min: 2
    max: 2
    weight: 50
  minecraft:dirt:
    min: 1
    max: 32
    weight: 100